"""Unit tests for DamodaranConnector — synthetic xlsx fixture."""

from __future__ import annotations

import io
import os
from datetime import date, datetime
from typing import TYPE_CHECKING

import openpyxl
import pytest

from sonar.connectors.damodaran import (
    COL_IMPLIED_FCFE,
    COL_IMPLIED_FCFE_SUSTAINABLE,
    COL_MONTH_ERP_SUSTAINABLE,
    COL_MONTH_ERP_T12M,
    COL_MONTH_SP500,
    COL_MONTH_START,
    COL_MONTH_TBOND_RATE,
    COL_SHEET,
    COL_YEAR,
    IMPLPREM_SHEET,
    DamodaranConnector,
    DamodaranERPRow,
    DamodaranMonthlyERPRow,
    _parse_monthly,
    _parse_year,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator
    from pathlib import Path

    from pytest_httpx import HTTPXMock


def _build_synthetic_xlsx(*, include_sustainable: bool = True) -> bytes:
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = COL_SHEET

    # 6 metadata rows, then header row at index 6, then data.
    for i in range(6):
        ws.append([f"meta{i}"])
    header = [COL_YEAR, "Earnings Yield", "Dividend Yield", COL_IMPLIED_FCFE]
    if include_sustainable:
        header.append(COL_IMPLIED_FCFE_SUSTAINABLE)
    ws.append(header)

    # Data rows 2020-2024.
    for year in range(2020, 2025):
        row = [year, 0.04, 0.02, 0.045 + (year - 2020) * 0.001]
        if include_sustainable:
            row.append(0.050 + (year - 2020) * 0.001)
        ws.append(row)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


class TestParseYear:
    def test_preferred_sustainable_column(self) -> None:
        body = _build_synthetic_xlsx(include_sustainable=True)
        result = _parse_year(body, 2024)
        assert isinstance(result, DamodaranERPRow)
        assert result.year == 2024
        assert result.source_column == COL_IMPLIED_FCFE_SUSTAINABLE
        assert result.implied_erp_decimal == pytest.approx(0.054)

    def test_fallback_to_fcfe_when_sustainable_missing(self) -> None:
        body = _build_synthetic_xlsx(include_sustainable=False)
        result = _parse_year(body, 2024)
        assert result is not None
        assert result.source_column == COL_IMPLIED_FCFE
        assert result.implied_erp_decimal == pytest.approx(0.049)

    def test_year_not_found_returns_none(self) -> None:
        body = _build_synthetic_xlsx()
        assert _parse_year(body, 1950) is None

    def test_header_row_required(self) -> None:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = COL_SHEET
        ws.append(["no-header-here"])
        buf = io.BytesIO()
        wb.save(buf)
        assert _parse_year(buf.getvalue(), 2024) is None


# ---------------------------------------------------------------------------
# Week 10 Sprint B — Monthly implied ERP archive
# ---------------------------------------------------------------------------


def _build_synthetic_monthly_xlsx(
    *,
    months: list[tuple[datetime, float | None, float | None, float, float]] | None = None,
    include_sustainable_col: bool = True,
    sheet_name: str = IMPLPREM_SHEET,
) -> bytes:
    """Build a synthetic implprem workbook.

    ``months`` is a list of ``(start_of_month_dt, erp_sust, erp_t12m,
    sp500, tbond)`` tuples. When ``erp_sust`` is ``None`` the sustainable
    column stays blank for that row (pre-2011 pattern).
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name

    # 2 meta rows then header.
    ws.append(["Damodaran Implied ERP Monthly"])
    ws.append(["Generated by tests"])
    header = [
        COL_MONTH_START,
        COL_MONTH_SP500,
        COL_MONTH_TBOND_RATE,
        "$ Riskfree Rate",
        "Ten-year average CF",
        "CF (Trailing 12 month)",
        "Normalized CF",
        "Expected growth rate",
    ]
    if include_sustainable_col:
        header.append(COL_MONTH_ERP_SUSTAINABLE)
    header.append(COL_MONTH_ERP_T12M)
    ws.append(header)

    # Damodaran's monthly file stores start-of-month as a naive datetime
    # in the xlsx cell — openpyxl refuses to serialise tz-aware datetimes,
    # so the test fixture must mirror the on-wire format.
    rows = (
        months
        if months is not None
        else [
            (datetime(2026, 1, 1), 0.0418, 0.0423, 6846.0, 0.0418),  # noqa: DTZ001
            (datetime(2026, 2, 1), 0.0417, 0.0425, 6939.0, 0.0426),  # noqa: DTZ001
        ]
    )
    for dt, erp_sust, erp_t12m, sp500, tbond in rows:
        row: list[object] = [dt, sp500, tbond, None, None, None, None, None]
        if include_sustainable_col:
            row.append(erp_sust)
        row.append(erp_t12m)
        ws.append(row)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


class TestParseMonthly:
    def test_prefers_sustainable_column(self) -> None:
        body = _build_synthetic_monthly_xlsx()
        result = _parse_monthly(body, 2026, 2, source_file="ERPFeb26.xlsx")
        assert isinstance(result, DamodaranMonthlyERPRow)
        assert result.start_of_month == date(2026, 2, 1)
        assert result.implied_erp_decimal == pytest.approx(0.0417)
        assert result.implied_erp_t12m_decimal == pytest.approx(0.0425)
        assert result.sp500_level == pytest.approx(6939.0)
        assert result.tbond_rate_decimal == pytest.approx(0.0426)
        assert result.source_file == "ERPFeb26.xlsx"

    def test_falls_back_to_t12m_when_sustainable_missing(self) -> None:
        body = _build_synthetic_monthly_xlsx(
            months=[
                (datetime(2010, 5, 1), None, 0.0533, 1100.0, 0.032),  # noqa: DTZ001
            ],
        )
        result = _parse_monthly(body, 2010, 5, source_file="ERPMay10.xlsx")
        assert result is not None
        assert result.implied_erp_decimal == pytest.approx(0.0533)

    def test_returns_none_when_both_erp_columns_null(self) -> None:
        body = _build_synthetic_monthly_xlsx(
            months=[(datetime(2008, 9, 1), None, None, 1252.0, 0.0372)],  # noqa: DTZ001
        )
        assert _parse_monthly(body, 2008, 9, source_file="ERPSep08.xlsx") is None

    def test_returns_none_when_month_absent(self) -> None:
        body = _build_synthetic_monthly_xlsx()
        assert _parse_monthly(body, 2025, 7, source_file="ERPJul25.xlsx") is None

    def test_returns_none_when_sheet_missing(self) -> None:
        body = _build_synthetic_monthly_xlsx(sheet_name="Wrong Sheet")
        assert _parse_monthly(body, 2026, 2, source_file="ERPFeb26.xlsx") is None


# ---------------------------------------------------------------------------
# Connector-level tests — full fetch round-trip via mocked HTTPX
# ---------------------------------------------------------------------------


@pytest.fixture
def tmp_damodaran_cache(tmp_path: Path) -> Path:
    d = tmp_path / "damodaran_cache"
    d.mkdir()
    return d


@pytest.fixture
async def damodaran_connector(tmp_damodaran_cache: Path) -> AsyncIterator[DamodaranConnector]:
    conn = DamodaranConnector(cache_dir=str(tmp_damodaran_cache))
    yield conn
    await conn.aclose()


async def test_fetch_monthly_resolves_latest_on_hit(
    httpx_mock: HTTPXMock, damodaran_connector: DamodaranConnector
) -> None:
    """Target month published on first try → single download."""
    body = _build_synthetic_monthly_xlsx()
    httpx_mock.add_response(
        method="GET",
        url="https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPFeb26.xlsx",
        content=body,
    )
    row = await damodaran_connector.fetch_monthly_implied_erp(2026, 2)
    assert row is not None
    assert row.start_of_month == date(2026, 2, 1)
    assert row.source_file == "ERPFeb26.xlsx"
    # Cache hit on second call — no extra download.
    row2 = await damodaran_connector.fetch_monthly_implied_erp(2026, 2)
    assert row2 is not None
    # Two historical months in synthetic body — same file serves both.
    row_jan = await damodaran_connector.fetch_monthly_implied_erp(2026, 1)
    assert row_jan is not None
    assert row_jan.source_file == "ERPFeb26.xlsx"


async def test_fetch_monthly_walks_backward_on_404(
    httpx_mock: HTTPXMock, damodaran_connector: DamodaranConnector
) -> None:
    """Target month 404 → walk backward until a published file is found."""
    httpx_mock.add_response(
        method="GET",
        url="https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPApr26.xlsx",
        status_code=404,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPMar26.xlsx",
        status_code=404,
    )
    httpx_mock.add_response(
        method="GET",
        url="https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPFeb26.xlsx",
        content=_build_synthetic_monthly_xlsx(),
    )
    row = await damodaran_connector.fetch_monthly_implied_erp(2026, 4)
    # File found is Feb 2026; target month Apr 2026 absent from workbook → None.
    assert row is None
    # But Feb 2026 is present in that workbook.
    row_feb = await damodaran_connector.fetch_monthly_implied_erp(2026, 2)
    assert row_feb is not None
    assert row_feb.source_file == "ERPFeb26.xlsx"


async def test_fetch_monthly_returns_none_when_lookback_exhausted(
    httpx_mock: HTTPXMock, damodaran_connector: DamodaranConnector
) -> None:
    """All lookback candidates 404 → resolver gives up, returns None."""
    for url in (
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPApr26.xlsx",
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPMar26.xlsx",
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPFeb26.xlsx",
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPJan26.xlsx",
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPDec25.xlsx",
        "https://pages.stern.nyu.edu/~adamodar/pc/implprem/ERPNov25.xlsx",
    ):
        httpx_mock.add_response(method="GET", url=url, status_code=404)
    assert await damodaran_connector.fetch_monthly_implied_erp(2026, 4) is None


async def test_fetch_monthly_rejects_bad_month(
    damodaran_connector: DamodaranConnector,
) -> None:
    with pytest.raises(ValueError, match="month out of range"):
        await damodaran_connector.fetch_monthly_implied_erp(2026, 13)
    with pytest.raises(ValueError, match="month out of range"):
        await damodaran_connector.fetch_monthly_implied_erp(2026, 0)


@pytest.mark.slow
@pytest.mark.filterwarnings("ignore::UserWarning")
async def test_live_canary_damodaran_monthly_implied_erp(
    tmp_damodaran_cache: Path,
) -> None:
    """Live probe against Damodaran NYU host — latest published file.

    Asserts the February 2026 row is within the [3.0 %, 6.0 %] band
    — a generous guard that catches both 0 (parser miss) and 10+
    (catastrophic schema drift). Also asserts ``source_file`` starts
    with ``ERP`` and ends ``.xlsx`` so URL-template drift triggers.

    Skips when ``DAMODARAN_LIVE_CANARY=0`` or unset only in CI; runs
    freely in the sprint run since the file is static monthly.
    """
    if os.environ.get("DAMODARAN_LIVE_CANARY") == "0":
        pytest.skip("DAMODARAN_LIVE_CANARY=0")
    conn = DamodaranConnector(cache_dir=str(tmp_damodaran_cache))
    try:
        # Feb 2026 is the current latest-published month per Sprint B
        # probe (2026-04-22). If Damodaran publishes a newer one the
        # resolver will prefer it; either way Feb 2026 must be inside
        # the workbook since every monthly file carries full history.
        row = await conn.fetch_monthly_implied_erp(2026, 2)
        assert row is not None
        assert row.source_file.startswith("ERP")
        assert row.source_file.endswith(".xlsx")
        assert 0.03 <= row.implied_erp_decimal <= 0.06
        assert row.sp500_level > 4000
        assert 0.02 <= row.tbond_rate_decimal <= 0.07
    finally:
        await conn.aclose()
